version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: echo "Hello World!"
  checks:
    docker:
      - image: circleci/circleci/python:3.6
    steps:
      - checkout
      - run: tox -e runtests -e codecov -e mypy

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - checks
