version: 2
jobs:
  check_py36:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: sudo pip install tox
      - run: cd src/ && tox
  check_py37:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: sudo pip install tox
      - run: cd src/ && tox


workflows:
  version: 2
  build_and_test:
    jobs:
      - check_py36
      - check_py37
