version: 2
jobs:
  checks:
    docker:
      - image: circleci/python:3.6
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: sudo pip install tox
      - run: cd src/ && tox


workflows:
  version: 2
  build_and_test:
    jobs:
      - checks
