version: 2
jobs:
  tests:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: sudo pip install tox
      - run: cd src/ && tox -e runtests -e codecov -e mypy
  mypy:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: sudo pip install tox
      - run: cd src/ && tox -e runtests -e codecov -e mypy
  codecov:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: sudo pip install tox
      - run: cd src/ && tox -e runtests -e codecov -e mypy

workflows:
  version: 2
  build_and_test:
    jobs:
      - tests
      - mypy
      - codecov
